require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'aqua' do
  config = use_native_modules!
  #config permissions

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  #
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'aquaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  # add_flipper_pods!('Flipper-Folly' => '2.3.0')
  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
end