const images = {
   // ic_wifi: require('./ic_wifi.png'),
   // ic_logo: require('./ic_logo.png'),
   // logo_aqua: require('./logo_aqua.png'),
   // ic_close: require('./ic_close.png'),
   // ic_bell: require('./ic_bell.png'),
   // ic_back: require('./ic_back.png'),
   // ic_error: require('./ic_error.png'),
   // ic_home: require('./ic_home.png'),
   // ic_check: require('./ic_check.png'),
   // rejected: require('./rejected.png'),
   // ic_arrows: require('./ic_arrows.png'),
   // no_image: require('./no-image.png'),
   // icon_barcode: require('./icon_barcode.png'),
   // ic_keyboard: require('./keyboard.png'),

   //icon figma
   ic_search: require('./search.png'),
   ic_clock: require('./clock.png'),
   ic_package: require('./package.png'),
   ic_approved: require('./ic_approved.png'),
   ic_rejected: require('./ic_rejected.png'),
   ic_eye: require('./ic_eye.png'),
   ic_eye_off: require('./ic_eye_off.png'),
   ic_calender: require('./ic_calender.png'),
   ic_close: require('./ic_close.png'),
   ic_filter: require('./ic_filter.png'),
   ic_history: require('./ic_history.png'),
   ic_more: require('./ic_more.png'),
   ic_pie_chart: require('./ic_pie_chart.png'),
   ic_refresh: require('./ic_refresh.png'),
   ic_registration: require('./ic_registration.png'),
   ic_vector: require('./ic_vector.png'),
   ic_wifi: require('./ic_wifi.png'),
   ic_logo: require('./ic_logo.png'),
   logo_aqua: require('./logo_aqua.png'),
   ic_close: require('./ic_close.png'),
   ic_bell: require('./ic_bell.png'),
   ic_back: require('./ic_back.png'),
   ic_profile: require('./ic_profile.png'),
   ic_profile_active: require('./ic_profile_active.png'),
   ic_history_active: require('./ic_history_active.png'),
   ic_registration_active: require('./ic_registration_active.png'),
   ic_ava: require('./ic_ava.png'),
   no_image: require('./no_image.png'),
   icon_barcode: require('./icon-barcode.png'),
   ic_keyboard: require('./keyboard.png'),
   ic_arrowleft: require('./arrow-left.png'),
   iC_arrowright: require('./arrow-right.png'),
   ic_barcodeBlue: require('./ic-barcodeblue.png'),
   ic_keyboard_Blue: require('./ic-Keyboard-blue.png'),
   ic_takeImage: require('./ic-image.png'),
   ic_trash: require('./ic-trash.png'),
   ic_nopicture: require('./ic_nopicture.png'),
   ic_discount: require('./ic_discount.png'),
   ic_message: require('./ic_message.png'),
   ic_camera: require('./ic_camera.png'),
}

export default images
